name: Update README

on:
  push:
    paths:
      - 'writeups/**'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Run update-readme script
      run: bash update-readme.sh

    - name: Commit and push if changed
      run: |
        git diff
        git config --global user.email "alexandre.tressel@epitech.eu"
        git config --global user.name "GitHub Action"
        git commit -am "Update README.md" || exit 0
        git push